name: Trying the custom actions

on: [push]

jobs:
  my-custom-action:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world step
        id: hello
        uses: eulerbutcooler/hello-world-js-action@main
        with:
          name: "Amaan"
      - name: Get output
        run: echo "The output is ${{ steps.hello.outputs.greeting }}"
