name: Trying out secrets
on:
  push:
    branches:
      - main
jobs:
  use-secret-as-input:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Custom action using secret
        run: |
          echo "using my secret api key: $API_KEY"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
