name: "Working with conditionals"
on:
  push:
    branches:
      - main
jobs:
  conditional-job:
    if: github.repository == 'eulerbutcooler/actions-practice'
    runs-on: ubuntu-latest
    steps:
      - name: "Hello world"
        run: echo "Hello world"
  i-wanna-go-to-the-moon:
    if: github.repository == 'eulerbutcooler/mazak'
    runs-on: ubuntu-latest
    steps:
      - name: "Hello moon"
        run: echo "Dont leave so soon"
