name: Second follow along github actions workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      name:
        description: "Name of the person to greet"
        required: true
        default: "amaan"
        type: string
      greeting:
        description: "Greeting message"
        required: true
        default: "Hello"
        type: string
      data:
        description: "Data to process"
        required: false
        type: string
jobs:
  greet:
    runs-on: ubuntu
    steps:
      - name: Greet the user
        run: echo "${{ github.events.inputs.greeting }} ${{ github.events.inputs.name }}!"
