name: "Webhook event example"
on:
  repository_dispatch:
    types:
      - webhook
jobs:
  respond-to-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Run a script
        run: 'echo "Event of type: $GITHUB_EVENT_NAME"'
